import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import apiFetch from '@/api/client';
import {
  pvrConfigPath,
  pvrMediaPath,
  pvrProgrammedPath,
  pvrProgrammedItemPath,
  pvrFinishedPath,
  pvrFinishedItemPath,
  pvrGeneratorItemPath,
} from '@/api/endpoints';
import { transformRecording } from '@/api/transformers';

const PVR_LIST_STALE_MS = 5 * 60_000;
const SIX_HOURS_S = 6 * 60 * 60;

const transformProgrammedList = (data) =>
  (data ?? []).map((raw) => transformRecording(raw, 'programmed'));

const buildFinishedSelector = (now) => (data) => {
  const cutoff = now - SIX_HOURS_S;
  return (data ?? [])
    .filter((raw) => raw.end >= cutoff)
    .map((raw) => transformRecording(raw, 'finished'));
};

/**
 * Invalidate both PVR list queries after a mutation. A single edit can
 * shift a recording between programmed and finished server-side, so we
 * always refresh both.
 * @param {import('@tanstack/react-query').QueryClient} queryClient - React Query client
 */
const invalidatePvrLists = (queryClient) => {
  queryClient.invalidateQueries({ queryKey: ['pvr', 'programmed'] });
  queryClient.invalidateQueries({ queryKey: ['pvr', 'finished'] });
};

/**
 * Fetch PVR recording configuration (margins)
 * @returns {{ data: { margin_before: number, margin_after: number }|undefined, isLoading: boolean }} Query result
 */
export const usePvrConfig = () =>
  useQuery({
    queryKey: ['pvr', 'config'],
    queryFn: () => apiFetch(pvrConfigPath()),
    staleTime: Infinity,
  });

/**
 * Fetch available PVR storage media
 * @returns {{ data: Array|undefined, isLoading: boolean }} Query result
 */
export const usePvrMedia = () =>
  useQuery({
    queryKey: ['pvr', 'media'],
    queryFn: () => apiFetch(pvrMediaPath()),
    staleTime: Infinity,
  });

/**
 * Create a programmed recording
 * @returns {import('@tanstack/react-query').UseMutationResult} Mutation result
 */
export const useCreateRecording = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (payload) =>
      apiFetch(pvrProgrammedPath(), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      }),
    onSuccess: () => invalidatePvrLists(queryClient),
  });
};

/**
 * Fetch the list of programmed (timer) recordings, normalised through
 * `transformRecording`. Includes occurrences generated by recurring
 * recorders.
 * @returns {import('@tanstack/react-query').UseQueryResult} Query result
 */
export const usePvrProgrammed = () =>
  useQuery({
    queryKey: ['pvr', 'programmed'],
    queryFn: () => apiFetch(pvrProgrammedPath()),
    staleTime: PVR_LIST_STALE_MS,
    select: transformProgrammedList,
  });

/**
 * Fetch the list of finished recordings, filtered to the last 6 hours so
 * the EPG overlay only shows recordings still close to the visible time
 * window. The `now` argument lets the caller drive the rolling cutoff
 * without refetching (the network result is shared, the selector slices).
 * @param {number} now - Reference timestamp in seconds, typically from useCurrentTime
 * @returns {import('@tanstack/react-query').UseQueryResult} Query result
 */
export const usePvrFinished = (now) =>
  useQuery({
    queryKey: ['pvr', 'finished'],
    queryFn: () => apiFetch(pvrFinishedPath()),
    staleTime: PVR_LIST_STALE_MS,
    select: buildFinishedSelector(now),
  });

/**
 * Update a recording (programmed or finished). The mutation accepts
 * `{ id, kind, payload }` and routes to the correct endpoint.
 * @returns {import('@tanstack/react-query').UseMutationResult} Mutation result
 */
export const useUpdateRecording = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, kind, payload }) => {
      const path = kind === 'finished'
        ? pvrFinishedItemPath(id)
        : pvrProgrammedItemPath(id);
      return apiFetch(path, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
    },
    onSuccess: () => invalidatePvrLists(queryClient),
  });
};

/**
 * Delete a recording. For a `running` programmed timer this is interpreted
 * as "stop" by the Freebox.
 * @returns {import('@tanstack/react-query').UseMutationResult} Mutation result
 */
export const useDeleteRecording = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, kind }) => {
      const path = kind === 'finished'
        ? pvrFinishedItemPath(id)
        : pvrProgrammedItemPath(id);
      return apiFetch(path, { method: 'DELETE' });
    },
    onSuccess: () => invalidatePvrLists(queryClient),
  });
};

/**
 * Lazily fetch a recording generator's metadata. Used to enrich the
 * tooltip of an occurrence (`generatorId != null`); a missing generator
 * surfaces as a 404 from the API and the caller renders without details.
 * @param {number|string|null} generatorId - Generator id, or null/undefined to skip
 * @returns {import('@tanstack/react-query').UseQueryResult} Query result
 */
export const usePvrGenerator = (generatorId) =>
  useQuery({
    queryKey: ['pvr', 'generator', generatorId],
    queryFn: () => apiFetch(pvrGeneratorItemPath(generatorId)),
    enabled: generatorId !== null && generatorId !== undefined,
    staleTime: PVR_LIST_STALE_MS,
  });
